name: Node js app deploy to MINIKUBE
on:
  push:
    branches: [ "minikube" ]
  pull_request:
    branches: [ "minikube" ]

jobs:
    deploy-minikube:
      runs-on: ubuntu-latest
      steps:
        - name: Build, tag, and push docker image to Minikube registry
          uses: actions/checkout@v3.5.3
      

          
        - name: Build and push Docker image
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
            docker build -t myimage:latest .
            docker push myimage:latest

        - name: Configure kubectl for Minikube
          run: minikube update-context

        - name: Deploy to Minikube
          run: |
            kubectl apply -f deployment.yaml
            kubectl apply -f service.yaml

        


    
      

